### ISSUE TITLE
Resize Page Header image

### ISSUE THREAD

**Issue by waynegraham** [waynegraham/clir_theme#22]
I think that, like the homepage, unless you have a lot of relevant and compelling imagery, you shouldn't rely on the header images too much. You can include them to keep pages from becoming too indistinct and samey, but I would scale down that top heading down to around quartre of its current size.

**Comment by kimisgold** [comment]
The size is controlled in the theme options under Page Title Bar, using the padding fields. For now, I've set it to 60px for both top and bottom in DLF.

**Comment by kimisgold** [comment]
The padding has now been applied to CLIR as well.
