### ISSUE TITLE
Menu width

### ISSUE THREAD

**Issue by waynegraham** [waynegraham/clir_theme#24]
Dropdown menu widths are narrow which makes the `Initiatives & Partnerships` menus go below the bottom of the web window at some sizes (e.g. iPad). Maybe add 50-100px to the dropdown width?

**Comment by kimisgold** [comment]
I restructured the dropdowns to support a full-width layout that uses flex columns. You have a lot of links with long labels, so I thought this might be a better way to use the space and give them breathing room.

**Comment by waynegraham** [comment]
This looks great!
