### ISSUE TITLE
Em.ma API key

### ISSUE THREAD

**Issue by waynegraham** [waynegraham/clir_theme#26]
I need an em.ma API key for signups for the CLIR newsletter signup form.

**Comment by Katsmi60** [comment]
Wayne, let me know if you are able to retrieve the information you need at this URL:  http://api.myemma.com/

**Comment by waynegraham** [comment]
I need the public/private key (see under Quickstart). Looks like you log in and click on API key. Once you get them, could you email them to me?

**Comment by Katsmi60** [comment]
Here you are… let me know if you need anything else.

Kathlin

**Comment by Katsmi60** [comment]
Sorry, I realize the second one is cut off. It is:

4911d137d76455f8a939


Kathlin
