### ISSUE TITLE
CLIR Header Menu

### ISSUE THREAD

**Issue by waynegraham** [waynegraham/clir_theme#6]
Set the content to be below the menu instead of transitioning from transparent to opaque.

**Comment by kimisgold** [comment]
I've set the DLF header to opaque via Header > Header Options >  Header Overlay "No". I tried doing the same with the main CLIR site, but it doesn't seem to be saving customization settings at the moment.

**Comment by waynegraham** [comment]
I'll look in to why the settings aren't saving and figure out what's going on...

**Comment by waynegraham** [comment]
I just double-checked and this seems to have been set, but I wonder if there aren't some caching issues? For now I've disabled the caching on it. Let me know if you are still seeing this behavior.

**Comment by kimisgold** [comment]
The changes seem to have taken now.
