### ISSUE TITLE
Footer Background

### ISSUE THREAD

**Issue by waynegraham** [waynegraham/clir_theme#8]
"I would maybe make it a more distinct background than that gray, some color distinct from the content. An idea would be to take the background color from "What is the DLF?" and use it for the footer, and use a much lighter version of that blue for that content area instead. That way you have your boldest colors bookending the content."

**Comment by kimisgold** [comment]
For the footer background-color, I used the teal background color that was initially used for the second section. I then realized it applied to both CLIR and DLF, and the teal clashed with DLF's blue. I wanted to bring in the CLIR burgundy to replace the teal in the footer for DLF. I couldn't find a great way to specify styles for DLF's footer, so the following styles currently live in the custom css option within DLF's theme options.

```
footer .footer-widget-area,
footer .footer-info-area {
        background-color: #991B45 !important;
        color: #f1a7c0;
}

footer .footer-widget-area .widget-title {
        color: #f1a7c0;
}

.footer-widget-area .widget-title:after {
        background-color: #f1a7c0;
}

footer .footer-widget-area a,
footer .footer-info-area a {
    color: #fff;
}
```
